server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://192.168.0.100/dawnflyc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: dawnflyc
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.0.100
    port: 6379
    password: dawnflyc
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

  jpa:
    show-sql: true
  thymeleaf:
    cache: false
